language: php

php:
  - 5.2.17
  - 5.3.29
  - 5.4.45
  - 5.5.38
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

services:
  - mysql

sudo: false

install:
  - export TZ=Asia/Tokyo # PHP <= 5.3
  - echo 'date.timezone = "Asia/Tokyo"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Disable Xdebug to avoid segfaults
  - phpenv config-rm xdebug.ini

  - cp config/ProjectConfiguration.class.php{.sample,}
  - cp config/OpenPNE.yml{.sample,}

  - git clone git://github.com/upsilon/opIgnoreKnownErrorsPlugin.git plugins/opIgnoreKnownErrorsPlugin

  - DBTYPE=mysql DBUSER=root DBPASS= DBHOST=localhost DBPORT= DBNAME=openpne DBSOCK=
  - for i in `seq 2`; do echo -e "$DBTYPE\n$DBUSER\n$DBPASS\n$DBHOST\n$DBPORT\n$DBNAME\n$DBSOCK\ny\n" | ./symfony openpne:install && break; done

  - ./symfony cc

  # PHP 5.2.x: Enable pre-installed apc.so
  - test $(phpenv version-name) = '5.2.17' && (echo 'extension=apc.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini) || true

  # PHP 5.3.x or higher: Install APCu
  - test $(phpenv version-name) != '5.2.17' && (yes '' | pecl install apcu-4.0.11) || true

  # Manually enable apcu.so for PHP 5.4.x: https://github.com/travis-ci/travis-ci/issues/5143
  - test $(phpenv version-name) = '5.4.45' && (echo 'extension=apcu.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini) || true

script:
  - ./symfony test:all
