<?php



/**
 * Skeleton subclass for performing query and update operations on the 'community_member' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.0-dev on:
 *
 * Wed Jul 13 23:36:50 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class CommunityMemberPeer extends BaseCommunityMemberPeer {
  static public function getCommunityIdsOfAdminByMemberId($memberId)
  {
    $objects = CommunityMemberPositionQuery::create()->findByMemberIdAndName($memberId, 'admin');

    $results = array();
    foreach ($objects as $obj)
    {
      $results[] = $obj->getCommunityId();
    }
    return $results;
  }

  static public function getCommunityMembersPreQuery($memberId)
  {
    $adminCommunityIds = self::getCommunityIdsOfAdminByMemberId($memberId);

    if (count($adminCommunityIds))
    {
      return CommunityMemberQuery::create()
        ->filterByCommunityId($adminCommunityIds)
        ->filterByIsPre(true);
    }

    return false;
  }

  static public function getCommunityMembersPre($memberId)
  {
    $q = self::getCommunityMembersPreQuery($memberId);

    if (!$q)
    {
      return array();
    }

    return $q->execute();
  }

  static public function countCommunityMembersPre($memberId)
  {
    $q = self::getCommunityMembersPreQuery($memberId);
    if (!$q)
    {
      return 0;
    }

    return $q->count();
  }
} // CommunityMemberPeer
