<?php



/**
 * Skeleton subclass for performing query and update operations on the 'member_config' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.0-dev on:
 *
 * Wed Jul 13 23:36:50 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class MemberConfigPeer extends BaseMemberConfigPeer {
  static public function setValue($memberId, $name, $value, $isDateTime = false)
  {
    $config = MemberConfigQuery::create()
      ->filterByName($name)
      ->filterByMemberId($memberId)
      ->findOneOrCreate();
    if ($isDateTime)
    {
      $config->setValueDatetime($value);
    }
    $config->setValue($value);
    $config->save();
  }
} // MemberConfigPeer
