<?php



/**
 * Skeleton subclass for representing a row from the 'member_profile' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.0-dev on:
 *
 * Wed Jul 13 23:36:50 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class MemberProfile extends BaseMemberProfile implements opAccessControlRecordInterface {
  public function __toString()
  {
    if ('date' !== $this->getFormType())
    {
      if ($this->getProfileOptionId())
      {
        $option = ProfileOptionQuery::create()->findPk($this->getProfileOptionId());
        return (string)$option->getValue();
      }

      $children = $this->getChildrenValues(true);
      if ($children)
      {
        return implode(', ', $children);
      }
    }

    return (string)$this->getValue();
  }

  public function construct()
  {
    if (!$this->isNew())
    {
      $this->mapValue('name', $this->Profile->getName());
      $this->mapValue('caption', $this->Profile->Translation['ja_JP']->caption);
    }

    return parent::construct();
  }

  public function getValue()
  {
    if ($this->getValueDatetime())
    {
      if (parent::getValue())
      {
        $obj = new DateTime($this->getValueDatetime());
        return $obj->format('Y-m-d');
      }

      return null;
    }

    if ($this->getProfile()->isPreset())
    {
      return parent::getValue();
    }
    elseif ('date' !== $this->getFormType() && $this->getProfileOptionId())
    {
      return $this->getProfileOptionId();
    }

    $children = $this->getChildrenValues();
    if ($children)
    {
      if ('date' === $this->getFormType())
      {
        if (count($children) == 3 && $children[0] && $children[1] && $children[2])
        {
          $obj = new DateTime();
          $obj->setDate($children[0], $children[1], $children[2]);
          return $obj->format('Y-m-d');
        }
        return null;
      }
      return $children;
    }

    return parent::getValue();
  }

  protected function getChildrenValues($isToString = false)
  {
    $values = array();

    if ($this->hasChildren())
    {
      $children = $this->getChildren();
      foreach ($children as $child)
      {
        if ('date' === $child->getFormType())
        {
          $values[] = $child->getValue();
        }
        elseif ($child->getProfileOptionId())
        {
          if ($isToString)
          {
            $option = ProfileOptionQuery::create()->findPk($child->getProfileOptionId());
            $values[] = $option->getValue();
          }
          else
          {
            $values[] = $child->getProfileOptionId();
          }
        }
      }
    }

    return $values;
  }

  public function getFormType()
  {
    return $this->getProfile()->getFormType();
  }

  public function setValue($value)
  {
    if ($this->getProfile() && $this->getProfile()->isSingleSelect() && !$this->getProfile()->isPreset())
    {
      $this->setProfileOptionId($value);
    }
    else
    {
      parent::setValue($value);
    }
  }

  public function preSave($event)
  {
    $modified = $this->getModifiedColumns();
    if (isset($modified['value_datetime']))
    {
      $this->setValue($this->getValueDatetime());
    }
    elseif ('date' === $this->getFormType() && isset($modified['value']) && $this->getProfile()->isPreset())
    {
      $this->setValueDatetime($this->getValue());
    }

    return parent::preSave();
  }

  public function postSave($event)
  {
    if ($this->getTreeKey())
    {
      $parent = MemberProfileQuery::create()->findPk($this->getTreeKey());
      if ($parent)
      {
        $this->insertAsLastChildOf($parent);
      }
    }
    else
    {
      $this->makeRoot();
    }
  }

  public function isViewable($memberId = null)
  {
    if (is_null($memberId))
    {
      $memberId = sfContext::getInstance()->getUser()->getMemberId();
    }

    switch ($this->getPublicFlag())
    {
      case ProfileTable::PUBLIC_FLAG_FRIEND:
        $relation = Doctrine::getTable('MemberRelationship')->retrieveByFromAndTo($this->getMemberId(), $memberId);
        if  ($relation && $relation->isFriend())
        {
          return true;
        }

        return ($this->getMemberId() == $memberId);

      case ProfileTable::PUBLIC_FLAG_PRIVATE:
        return false;

      case ProfileTable::PUBLIC_FLAG_SNS:
        return (bool)$memberId;

      case ProfileTable::PUBLIC_FLAG_WEB:
        return ($this->Profile->is_public_web) ? true : (bool)$memberId;
    }
  }

  public function clearChildren()
  {
    if ($this->getTreeKey() && $this->getNode()->hasChildren())
    {
      $children = $this->getNode()->getChildren();
      $children->delete();
    }
  }

  public function getPublicFlag()
  {
    $profile = $this->getProfile();
    if ($profile->getIsEditPublicFlag())
    {
      return $this->_data['public_flag'] ? $this->_data['public_flag'] : $profile->getDefaultPublicFlag();
    }

    return $profile->getDefaultPublicFlag();
  }

  public function generateRoleId(Member $member)
  {
    $relation = Doctrine::getTable('MemberRelationship')->retrieveByFromAndTo($this->Member->id, $member->id);

    if ($this->Member->id === $member->id)
    {
      return 'self';
    }
    elseif ($relation)
    {
      if ($relation->getIsAccessBlock())
      {
        return 'blocked';
      }
      elseif ($relation->getIsFriend())
      {
        return 'friend';
      }
    }

    return 'everyone';
  }
} // MemberProfile
