<?php



/**
 * Skeleton subclass for representing a row from the 'profile_option_i18n' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.0-dev on:
 *
 * Wed Jul 13 23:36:50 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class ProfileOptionI18n extends BaseProfileOptionI18n {

} // ProfileOptionI18n
