<?php



/**
 * Skeleton subclass for representing a row from the 'profile' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.0-dev on:
 *
 * Wed Jul 13 23:36:49 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Profile extends BaseProfile {
 /**
  * get options array
  *
  * @return array
  */
  public function getOptionsArray()
  {
    if ($this->isPreset())
    {
      return $this->getPresetOptionsArray();
    }

    $result = array();

    $options = $this->getProfileOption();

    foreach ($options as $option)
    {
      $result[$option->getId()] = $option->getValue();
    }

    return $result;
  }

 /**
  * get present options array
  *
  * @return array
  */
  public function getPresetOptionsArray()
  {
    $result = array();
    $config = $this->getPresetConfig();

    if (!empty($config['Choices']))
    {
      $result = array_combine($config['Choices'], $config['Choices']);
    }

    return $result;
  }

 /**
  * get raw preset name
  *
  * @return string
  */
  public function getRawPresetName()
  {
    if (!$this->isPreset())
    {
      return false;
    }

    $name = substr($this->getName(), strlen('op_preset_'));

    if ('region_select' === $this->getFormType()
        && 'string' !== $this->getValueType())
    {
      $name .= '_'.$this->getValueType();
    }

    return $name;
  }

 /**
  * get preset config
  *
  * @return array
  */
  public function getPresetConfig()
  {
    $list = opToolkit::getPresetProfileList();
    if (!empty($list[$this->getRawPresetName()]))
    {
      return $list[$this->getRawPresetName()];
    }

    return array();
  }

 /**
  * Checks if the profile is preset.
  *
  * @return boolean
  */
  public function isPreset()
  {
    return (0 === strpos($this->getName(), 'op_preset_'));
  }
} // Profile
