<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sns_config' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.0-dev on:
 *
 * Wed Jul 13 23:36:50 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class SnsConfigPeer extends BaseSnsConfigPeer {
  static public function getAll()
  {
    static $configs = null;
    if (null === $configs)
    {
      $configs = SnsConfigQuery::create()
        ->find()
        ->toKeyValue('Name', 'Value');
    }

    return $configs;
  }

  static public function get($name, $default = null)
  {
    $configs = self::getAll();
    $value = isset($configs[$name]) ? $configs[$name] : null;

    return null === $value ? $default : $value;
  }
} // SnsConfigPeer
