<?php



/**
 * Skeleton subclass for representing a row from the 'sns_term_i18n' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.0-dev on:
 *
 * Wed Jul 13 23:49:23 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class SnsTermI18n extends BaseSnsTermI18n {

} // SnsTermI18n
