<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sns_term' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.0-dev on:
 *
 * Wed Jul 13 23:49:23 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class SnsTermPeer extends BaseSnsTermPeer {
  static public function get($name, $application = null, $culture = null)
  {
    $fronting = false;
    if (preg_match('/[A-Z]/', $name[0]))
    {
      $fronting = true;
      $name = strtolower($name[0]).substr($name, 1);
    }

    $query = SnsTermQuery::create()
      ->filterByName($name);

    if ($application)
    {
      $query->filterByApplication($application);
    }

    if ($culture)
    {
      $query->leftJoinSnsTermI18n();
      $query->addJoinCondition('SnsTermI18n', 'SnsTermI18n.Culture = ?', $culture);
    }

    $result = $query->findOne();

    if ($result && $fronting)
    {
      $result->fronting();
    }

    return $result;
  }
} // SnsTermPeer
